# Generated by Django 4.1.2 on 2022-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notescontroller",
            name="content",
            field=models.CharField(max_length=1000),
        ),
    ]
