# Generated by Django 4.1.2 on 2022-10-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0002_alter_notescontroller_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notescontroller",
            name="content",
            field=models.TextField(),
        ),
    ]
