# Generated by Django 4.1.2 on 2022-10-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0003_alter_notescontroller_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notescontroller",
            name="content",
        ),
    ]
