# Generated by Django 4.1.2 on 2022-10-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0005_notescontroller_succes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notescontroller",
            old_name="succes",
            new_name="success",
        ),
    ]
